# This is a basic workflow to help you get started with Actions

name: tryout buildsystem actions

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      swpath: "/release/sw.js"      
      webmanifest_pattern: manifest.webmanifest
      webmanifest_file_path: /release/manifest.webmanifest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: replace env vars in files
        uses: sandersaares-actions/expand-tokens@master
        env:
          sw_file_path: $swpath
        with: 
          path: .
          filenames: pwa.js; story.html
          recursive: true

      # - name: copy files
      #   uses: canastro/copy-file-action@master
      #   with: 
      #     source: "mainsite/js/pwa.js"
      #     target: "pwa_replaced_env_vars.js"

      # m4 kann mit templates verwendet werden
      - name: replace manifest path
        run: sed -i "s|manifest.webmanifest|/release/manifest.webmanifest" story.html
      # Runs a single command using the runners shell
      - name: print out root files
        run: |
          cat story.html
          cat pwa.js
          
            
      # Runs a set of commands using the runners shell
      - name: print out subfolder files
        run: |          
          cat mainsite/story.html
          cat mainsite/js/pwa.js
